<?php
/** @var $this Due_Payments_Block_Form_CC */
?>

<?php $_code = $this->getMethodCode() ?>
<script type="text/javascript">
    initDue('<?php echo $this->getDueEnv(); ?>', '<?php echo $this->getDueAppId(); ?>', '<?php echo $this->getDueRailType(); ?>');

    var form = document.getElementById('payment_form_<?php echo $_code ?>');
    if (form) {
        form.onclick = enableInputs;
    }

    // Default Magento Onepage checkout
    var btn = document.getElementById('payment-buttons-container');
    if (btn) btn = btn.getElementsByTagName('button');
    if (btn && btn[0]) {
        btn = btn[0];
    }
    if (btn) {
        btn.onclick = function() {
            if (payment.currentMethod !== '<?php echo $_code ?>') {
                return payment.save();
            }

            var validator;
            var mode = $$('#payment_form_due_cc  input::checked[name="payment[cc_mode]"]').first().value;
            switch (mode) {
                case 'saved_card':
                    validator = new Validation('saved-cards');
                    if (validator.validate()) {
                        payment.save();
                    }
                    break;
                case 'new_card':
                    //var validator = new Validation('payment_form_<?php echo $_code ?>');
                    validator = new Validation('new-card');
                    if (validator.validate()) {
                        createDueToken(function(err, card) {
                            if (err) {
                                alert(err);
                            } else {
                                payment.save();
                            }
                        });
                    }
                    break;
            }


        };
    }
</script>
<script type="text/javascript">
    $('payment_form_due_cc').on('change', '.cc_mode', function(el) {
        switch ($(el.target).value) {
            case 'saved_card':
                $('new-card').hide();
                $('saved-cards').show();
                break;
            case 'new_card':
                $('saved-cards').hide();
                $('new-card').show();
                break;
        }
    });
</script>

<?php $cards = $this->getStoredCards(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <!-- Start Saved Cards -->
    <?php if ($this->isStoreCardsEnabled() && $this->isCustomerLoggedIn() && count($cards) > 0): ?>
    <li>
        <input type="radio" name="payment[cc_mode]" value="saved_card" class="radio cc_mode validate-one-required-by-name" id="saved_card" checked>
        <label for="saved_card">
            <span class="type saved"><?php echo $this->__('Use a saved card'); ?></span>
        </label>
    </li>
    <li>
        <ul id="saved-cards">
            <?php foreach ($cards as $id => $card): ?>
                <li class="saved-cards-list">
                    <input type="radio" name="payment[cc_saved]" id="card_<?php echo $card['card_id']; ?>" value="<?php echo $card['card_id']; ?>" class="radio validate-one-required-by-name" <?php echo $id === 0 ? 'checked' : ''; ?>/>
                    <label for="card_<?php echo $card['card_id']; ?>">
                        <?php echo $this->formatCard($card); ?>
                    </label>
                </li>
            <?php endforeach; ?>
        </ul>
    </li>
    <li>
        <input type="radio" name="payment[cc_mode]" value="new_card" class="radio cc_mode validate-one-required-by-name" id="new_card">
        <label for="new_card">
            <span class="type new"><?php echo $this->__('Use a new card'); ?></span>
        </label>
    </li>
    <?php else: ?>
        <input type="radio" name="payment[cc_mode]" value="new_card" class="cc_mode" id="new_card" checked style="display: none;" />
    <?php endif; ?>
    <!-- End Saved Cards -->

    <li>
        <!-- Start New Card -->
        <ul id="new-card" style="<?php echo $this->isStoreCardsEnabled() && $this->isCustomerLoggedIn() && count($cards) > 0 ? 'display:none;' : '' ?>">
            <li>
                <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
                <div class="input-box">
                    <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="due-input required-entry validate-cc-type-select">
                        <option value=""><?php echo $this->__('--Please Select--')?></option>
                        <?php $_ccType = $this->getInfoData('cc_type') ?>
                        <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                            <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Credit Card Number')) ?>" class="input-text due-input validate-cc-number validate-cc-type" value="" />
                </div>
            </li>
            <li id="<?php echo $_code ?>_cc_type_exp_div">
                <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
            <?php echo $this->getChildHtml() ?>
            <?php if($this->hasVerification()): ?>
                <li id="<?php echo $_code ?>_cc_type_cvv_div">
                    <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <input type="text" title="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Card Verification Number')) ?>" class="input-text due-input cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                        </div>
                        <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    </div>
                </li>
            <?php endif; ?>

            <li id="<?php echo $_code ?>_cc_mail">
                <label for="<?php echo $_code ?>_cc_mail" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_cc_mail" name="payment[cc_mail]" title="<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Email Address')) ?>" class="input-text due-input required-entry validate-email" value="" />
                </div>
            </li>

            <?php if ($this->isStoreCardsEnabled() && $this->isCustomerLoggedIn()): ?>
                <li class="form-alt">
                    <label for="<?php echo $_code ?>_cc_save_card">
                        <input type="checkbox" id="<?php echo $_code ?>_cc_save_card" value="1" name="payment[cc_save_card]" class="checkbox" />
                        <?php echo $this->__('Save this card to streamline further purchases with Due.com') ?>
                    </label>
                </li>
            <?php else: ?>
                <input type="hidden" name="payment[cc_save_card]" value="0" />
            <?php endif; ?>
        </ul>
        <!-- End New Card -->
    </li>
</ul>
